In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('heart.csv')
data

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  \
0     40   M           ATA        140          289          0     Normal   
1     49   F           NAP        160          180          0     Normal   
2     37   M           ATA        130          283          0         ST   
3     48   F           ASY        138          214          0     Normal   
4     54   M           NAP        150          195          0     Normal   
..   ...  ..           ...        ...          ...        ...        ...   
913   45   M            TA        110          264          0     Normal   
914   68   M           ASY        144          193          1     Normal   
915   57   M           ASY        130          131          0     Normal   
916   57   F           ATA        130          236          0        LVH   
917   38   M           NAP        138          175          0     Normal   

     MaxHR ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0      172              N      0.0       Up             0  
1      156              N      1.0     Flat             1  
2       98              N      0.0       Up             0  
3      108              Y      1.5     Flat             1  
4      122              N      0.0       Up             0  
..     ...            ...      ...      ...           ...  
913    132              N      1.2     Flat             1  
914    141              N      3.4     Flat             1  
915    115              Y      1.2     Flat             1  
916    174              N      0.0     Flat             1  
917    173              N      0.0       Up             0  

[918 rows x 12 columns]

In [3]:
data.head()

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  MaxHR  \
0   40   M           ATA        140          289          0     Normal    172   
1   49   F           NAP        160          180          0     Normal    156   
2   37   M           ATA        130          283          0         ST     98   
3   48   F           ASY        138          214          0     Normal    108   
4   54   M           NAP        150          195          0     Normal    122   

  ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0              N      0.0       Up             0  
1              N      1.0     Flat             1  
2              N      0.0       Up             0  
3              Y      1.5     Flat             1  
4              N      0.0       Up             0

In [4]:
data.describe()

Age   RestingBP  Cholesterol   FastingBS       MaxHR  \
count  918.000000  918.000000   918.000000  918.000000  918.000000   
mean    53.510893  132.396514   198.799564    0.233115  136.809368   
std      9.432617   18.514154   109.384145    0.423046   25.460334   
min     28.000000    0.000000     0.000000    0.000000   60.000000   
25%     47.000000  120.000000   173.250000    0.000000  120.000000   
50%     54.000000  130.000000   223.000000    0.000000  138.000000   
75%     60.000000  140.000000   267.000000    0.000000  156.000000   
max     77.000000  200.000000   603.000000    1.000000  202.000000   

          Oldpeak  HeartDisease  
count  918.000000    918.000000  
mean     0.887364      0.553377  
std      1.066570      0.497414  
min     -2.600000      0.000000  
25%      0.000000      0.000000  
50%      0.600000      1.000000  
75%      1.500000      1.000000  
max      6.200000      1.000000

In [5]:
data.columns

Index(['Age', 'Sex', 'ChestPainType', 'RestingBP', 'Cholesterol', 'FastingBS',
       'RestingECG', 'MaxHR', 'ExerciseAngina', 'Oldpeak', 'ST_Slope',
       'HeartDisease'],
      dtype='object')

In [6]:
data.shape

(918, 12)

# outliers

In [7]:
data[data.Cholesterol>(data.Cholesterol.mean()+3*data.Cholesterol.std())].shape

(3, 12)

In [8]:
data.Cholesterol.mean()

198.7995642701525

In [9]:
data.Cholesterol.std()

109.38414455220337

In [22]:
y=198.7995642701525+3*(109.38414455220337)
y

526.9519979267626

In [10]:
y=data[data.Cholesterol<(data.Cholesterol.mean()+3*data.Cholesterol.std())]


In [22]:
y.shape

(915, 12)

In [11]:
data.columns

Index(['Age', 'Sex', 'ChestPainType', 'RestingBP', 'Cholesterol', 'FastingBS',
       'RestingECG', 'MaxHR', 'ExerciseAngina', 'Oldpeak', 'ST_Slope',
       'HeartDisease'],
      dtype='object')

In [12]:
data[data.FastingBS>(data.FastingBS.mean()+3*data.FastingBS.std())]

Empty DataFrame
Columns: [Age, Sex, ChestPainType, RestingBP, Cholesterol, FastingBS, RestingECG, MaxHR, ExerciseAngina, Oldpeak, ST_Slope, HeartDisease]
Index: []

In [13]:
data[data.MaxHR>(data.MaxHR.mean()+3*data.MaxHR.std())]

Empty DataFrame
Columns: [Age, Sex, ChestPainType, RestingBP, Cholesterol, FastingBS, RestingECG, MaxHR, ExerciseAngina, Oldpeak, ST_Slope, HeartDisease]
Index: []

In [14]:
data[data.Oldpeak>(data.Oldpeak.mean()+3*data.Oldpeak.std())].shape


(6, 12)

In [15]:
old =data[data.Oldpeak<=(data.Oldpeak.mean()+3*data.Oldpeak.std())]
old.shape

(912, 12)

In [16]:
data.Oldpeak.mean()

0.8873638344226579

In [17]:
3*data.Oldpeak.std()

3.19971045314797

In [34]:
0.8873638344226579+3.19971045314797

4.087074287570628

In [18]:
data[data.RestingBP>(data.RestingBP.mean()+3*data.RestingBP.std())].shape

(7, 12)

In [19]:
data.dtypes

Age                 int64
Sex                object
ChestPainType      object
RestingBP           int64
Cholesterol         int64
FastingBS           int64
RestingECG         object
MaxHR               int64
ExerciseAngina     object
Oldpeak           float64
ST_Slope           object
HeartDisease        int64
dtype: object

In [20]:
data.Sex.unique()

array(['M', 'F'], dtype=object)

In [47]:
data.ChestPainType.unique()

array(['ATA', 'NAP', 'ASY', 'TA'], dtype=object)

In [48]:
data.RestingECG.unique()

array(['Normal', 'ST', 'LVH'], dtype=object)

In [49]:
data.ExerciseAngina.unique()

array(['N', 'Y'], dtype=object)

In [50]:
data.ST_Slope.unique()

array(['Up', 'Flat', 'Down'], dtype=object)

In [22]:
df= data.copy()

In [26]:
df.ExerciseAngina.replace(
{
    'Y':1,
    'N':0
},
    inplace = True)


In [27]:
df.ST_Slope.replace(
    {
        'Up':1,
       'Flat':2,
     'Down':3},
    inplace=True)

In [28]:
df.RestingECG.replace(
    {
        'Normal':1,
        'ST':2,
        'LVH':3},
    inplace=True)

In [90]:
df.head()

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS  RestingECG  \
0   40   M           ATA        140          289          0           1   
1   49   F           NAP        160          180          0           1   
2   37   M           ATA        130          283          0           2   
3   48   F           ASY        138          214          0           1   
4   54   M           NAP        150          195          0           1   

   MaxHR  ExerciseAngina  Oldpeak  ST_Slope  HeartDisease  
0    172               0      0.0         1             0  
1    156               0      1.0         2             1  
2     98               0      0.0         1             0  
3    108               1      1.5         2             1  
4    122               0      0.0         1             0

In [53]:
df1=pd.get_dummies(df, drop_first=True)
df1

Age  RestingBP  Cholesterol  FastingBS  RestingECG  MaxHR  \
0     40        140          289          0           1    172   
1     49        160          180          0           1    156   
2     37        130          283          0           2     98   
3     48        138          214          0           1    108   
4     54        150          195          0           1    122   
..   ...        ...          ...        ...         ...    ...   
913   45        110          264          0           1    132   
914   68        144          193          1           1    141   
915   57        130          131          0           1    115   
916   57        130          236          0           3    174   
917   38        138          175          0           1    173   

     ExerciseAngina  Oldpeak  ST_Slope  HeartDisease  Sex_M  \
0                 0      0.0         1             0   True   
1                 0      1.0         2             1  False   
2                 0      0.0         1             0   True   
3                 1      1.5         2             1  False   
4                 0      0.0         1             0   True   
..              ...      ...       ...           ...    ...   
913               0      1.2         2             1   True   
914               0      3.4         2             1   True   
915               1      1.2         2             1   True   
916               0      0.0         2             1  False   
917               0      0.0         1             0   True   

     ChestPainType_ATA  ChestPainType_NAP  ChestPainType_TA  
0                 True              False             False  
1                False               True             False  
2                 True              False             False  
3                False              False             False  
4                False               True             False  
..                 ...                ...               ...  
913              False              False              True  
914              False              False             False  
915              False              False             False  
916               True              False             False  
917              False               True             False  

[918 rows x 14 columns]

In [91]:
x= df1.drop('HeartDisease',axis='columns')
y =df1.HeartDisease
x.head()

Age  RestingBP  Cholesterol  FastingBS  RestingECG  MaxHR  ExerciseAngina  \
0   40        140          289          0           1    172               0   
1   49        160          180          0           1    156               0   
2   37        130          283          0           2     98               0   
3   48        138          214          0           1    108               1   
4   54        150          195          0           1    122               0   

   Oldpeak  ST_Slope  Sex_M  ChestPainType_ATA  ChestPainType_NAP  \
0      0.0         1   True               True              False   
1      1.0         2  False              False               True   
2      0.0         1   True               True              False   
3      1.5         2  False              False              False   
4      0.0         1   True              False               True   

   ChestPainType_TA  
0             False  
1             False  
2             False  
3             False  
4             False

In [59]:
y.head()

0    0
1    1
2    0
3    1
4    0
Name: HeartDisease, dtype: int64

In [92]:
from sklearn.preprocessing import StandardScaler
scaler =StandardScaler()
x_scld = scaler.fit_transform(x)
x_scld

array([[-1.4331398 ,  0.41090889,  0.82507026, ...,  2.07517671,
        -0.53283777, -0.22967867],
       [-0.47848359,  1.49175234, -0.17196105, ..., -0.48188667,
         1.87674385, -0.22967867],
       [-1.75135854, -0.12951283,  0.7701878 , ...,  2.07517671,
        -0.53283777, -0.22967867],
       ...,
       [ 0.37009972, -0.12951283, -0.62016778, ..., -0.48188667,
        -0.53283777, -0.22967867],
       [ 0.37009972, -0.12951283,  0.34027522, ...,  2.07517671,
        -0.53283777, -0.22967867],
       [-1.64528563,  0.30282455, -0.21769643, ..., -0.48188667,
         1.87674385, -0.22967867]])

In [67]:
from sklearn.model_selection import train_test_split

In [74]:
x_train,x_test,y_train,y_test = train_test_split(x_scld,y,test_size=0.20,random_state=30)

In [76]:
x_train

array([[-1.85743145, -1.21035628, -1.81843477, ..., -0.48188667,
        -0.53283777, -0.22967867],
       [-1.53921271,  0.30282455,  0.193922  , ..., -0.48188667,
         1.87674385, -0.22967867],
       [-1.64528563, -1.21035628,  0.82507026, ..., -0.48188667,
        -0.53283777, -0.22967867],
       ...,
       [ 1.64297467,  0.41090889,  0.36771645, ..., -0.48188667,
        -0.53283777,  4.35390879],
       [ 1.32475593, -0.66993455, -1.81843477, ..., -0.48188667,
         1.87674385, -0.22967867],
       [ 0.05188098,  0.41090889,  0.36771645, ..., -0.48188667,
        -0.53283777, -0.22967867]])

In [77]:
x_test

array([[ 0.15795389,  0.41090889,  0.16648077, ..., -0.48188667,
        -0.53283777, -0.22967867],
       [ 0.2640268 ,  2.03217406,  1.73063081, ..., -0.48188667,
        -0.53283777, -0.22967867],
       [-0.79670232,  0.08665586,  1.01715886, ..., -0.48188667,
        -0.53283777, -0.22967867],
       ...,
       [-0.05419193,  0.41090889,  0.40430475, ..., -0.48188667,
        -0.53283777, -0.22967867],
       [-1.4331398 , -0.66993455,  2.44410275, ..., -0.48188667,
        -0.53283777, -0.22967867],
       [-1.96350436, -0.34568152,  0.76104073, ..., -0.48188667,
        -0.53283777, -0.22967867]])

In [79]:
x_train.shape

(734, 13)

In [81]:
x_test.shape

(184, 13)

In [85]:
from sklearn.ensemble import RandomForestClassifier
model_rf= RandomForestClassifier()
model_rf.fit(x_train,y_train)
model_rf.score(x_test,y_test)

0.8586956521739131

# Use PCI to reduce Some Columns

In [86]:
x

Age  RestingBP  Cholesterol  FastingBS  RestingECG  MaxHR  \
0     40        140          289          0           1    172   
1     49        160          180          0           1    156   
2     37        130          283          0           2     98   
3     48        138          214          0           1    108   
4     54        150          195          0           1    122   
..   ...        ...          ...        ...         ...    ...   
913   45        110          264          0           1    132   
914   68        144          193          1           1    141   
915   57        130          131          0           1    115   
916   57        130          236          0           3    174   
917   38        138          175          0           1    173   

     ExerciseAngina  Oldpeak  ST_Slope  Sex_M  ChestPainType_ATA  \
0                 0      0.0         1   True               True   
1                 0      1.0         2  False              False   
2                 0      0.0         1   True               True   
3                 1      1.5         2  False              False   
4                 0      0.0         1   True              False   
..              ...      ...       ...    ...                ...   
913               0      1.2         2   True              False   
914               0      3.4         2   True              False   
915               1      1.2         2   True              False   
916               0      0.0         2  False               True   
917               0      0.0         1   True              False   

     ChestPainType_NAP  ChestPainType_TA  
0                False             False  
1                 True             False  
2                False             False  
3                False             False  
4                 True             False  
..                 ...               ...  
913              False              True  
914              False             False  
915              False             False  
916              False             False  
917               True             False  

[918 rows x 13 columns]

In [94]:
from sklearn.decomposition import PCA

pca = PCA(0.95)
X_pca = pca.fit_transform(x)
X_pca

array([[ 92.31079119, -29.44316816],
       [-17.14409666, -13.7394731 ],
       [ 81.90733808,  38.22442746],
       ...,
       [-69.0041927 ,  17.33216411],
       [ 39.2077941 , -33.59642907],
       [-21.43805605, -37.21419015]])

In [98]:
x_train_pca,x_test_pca,y_train,y_test= train_test_split(X_pca,y,test_size=0.30,random_state=30)

array([[  -3.92911577,  -16.22226456],
       [  12.44138729,    2.68341967],
       [-113.63967283,  -11.51801705],
       ...,
       [  40.94313903,   -7.09425242],
       [-199.72164752,    4.80650883],
       [  41.59051422,  -18.23136427]])

In [106]:
from sklearn.ensemble import RandomForestClassifier
model_rf = RandomForestClassifier()
model_rf.fit(x_train_pca, y_train)
model_rf.score(x_test_pca, y_test)

0.7028985507246377